### Numpy Practice
This notebook is a collection of Numpy exercises from the , which can be found [here](https://www.w3resource.com/python-exercises/numpy/index.php). The exercises are meant to help me get familiar with numpy and its functions.

Source of Learning  can ne found on [Geeksforgeeks](https://www.geeksforgeeks.org/numpy-tutorial//)

In [1]:
#load  libaray
import numpy as np
import matplotlib.pyplot as plt # type: ignore

In [3]:
# Write a Numpy program to get the Numpy version and show the Numpy build configuration. 
print(np.__version__)
print(np.show_config())

1.26.1
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2300277146320
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.1
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.3
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


In [4]:
#Write a NumPy program to get help with the add function.
x = np.info(np.add)
print(x)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [6]:
#3. Write a NumPy program to test whether none of the elements of a given array are zero.  
a = np.array([1,2,3,4])
b = np.array([0,1,2,3])
print(a)
print(np.all(a))
print(b)
print(np.all(b))

[1 2 3 4]
True
[0 1 2 3]
False


In [11]:
# Write a NumPy program to test if any of the elements of a given array are non-zero.
arr1 = np.array([1,2,3,4])
arr2 = np.array([0,0,0,0])
print(arr1)
print(np.any(arr1))
print(arr2)
print(np.any(arr2))


[1 2 3 4]
True
[0 0 0 0]
False


In [12]:
#Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).

arr2 = np.array([1,2,3,np.nan])
print(arr2)
print(np.isfinite(arr2))

[ 1.  2.  3. nan]
[ True  True  True False]


In [16]:
# Write a NumPy program to test elements-wise for positive or negative infinity.
arr3 = np.array([1,2, -3, -5, 19, 3,np.inf])
print(arr3)
print(np.isposinf(arr3))
print(np.isneginf(arr3))

[ 1.  2. -3. -5. 19.  3. inf]
[False False False False False False  True]
[False False False False False False False]


In [17]:
# Write a NumPy program to test element-wise for NaN of a given array.
arr4 = np.array([1,2,3,np.nan])
print(arr4)
print(np.isnan(arr4))


[ 1.  2.  3. nan]
[False False False  True]


In [19]:
# Write a  NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not.
arr5 = np.array([1,2,3,4,5+1j,6,7,8,9,10])
print(arr5)
print(np.iscomplex(arr5))
print(np.isreal(arr5))
print(np.isscalar(3))
print(np.isscalar([3]))


[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+1.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j
 10.+0.j]
[False False False False  True False False False False False]
[ True  True  True  True False  True  True  True  True  True]
True
False


In [23]:
# Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.
arr6 = np.array([1,2,3,4,5])
arr7 = np.array([1,2,10,4,5])
print(np.allclose(arr6,arr7))
print(np.allclose(arr6,arr7, atol=0.1))

False
False


In [24]:
# Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.
arr8 = np.array([1,2,3,4,5])
arr9 = np.array([1,2,10,4,5])
print(np.greater(arr8,arr9))
print(np.greater_equal(arr8,arr9))
print(np.less(arr8,arr9))
print(np.less_equal(arr8,arr9))



[False False False False False]
[ True  True False  True  True]
[False False  True False False]
[ True  True  True  True  True]


In [25]:
# Write a  NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays. 
arr10 = np.array([1,2,3,4,5])
arr11 = np.array([1,2,10,4,5])
print(np.equal(arr10,arr11))


[ True  True False  True  True]


In [33]:
# Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array. 
arr11 = np.array([1,7,13,105])
print("%d bytes" % (arr11.size * arr11.itemsize)) 

16 bytes


In [3]:

#Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.  
arr12 = np.zeros(10)
print(arr12)
arr13 = np.ones(10)
print(arr13)
arr14 = np.ones(10)*5
print(arr14)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [4]:
#  Write a NumPy program to create an array of integers from 30 to 70. 
arr14 = np.arange(30,71)
print(arr14)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [9]:
# Write a NumPy program to create an array of all even integers from 30 to 70.
arr15 = np.arange(30,71,2)
print(arr15)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [14]:
# Write a NumPy program to create a 3x3 identity matrix. 
arr16 = np.identity(3)
print(arr16)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
# Write a NumPy program to generate a random number between 0 and 1. 
arr17 = np.random.normal(0,1,1)
print(arr17)

[-1.29932867]


In [2]:
# Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
arr18 = np.random.normal(0,1,15)
print(arr18)

[ 0.33787959  0.86094364 -0.30979504  1.42011989 -1.71156217  0.95874455
 -0.80417521  0.8177373   0.36069969 -0.23484703  1.20506942  1.72180142
 -2.93006046 -0.70228486 -1.61762032]


In [3]:
# Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last. 
arr19 = np.arange(15,55)
print(arr19[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [19]:
arr20 =  np.arange(10, 22).reshape((3, 4))
for i in np.nditer(arr20):
    print(i, end=' ')


10 11 12 13 14 15 16 17 18 19 20 21 

[14. 15. 16. 17.]
